### ISSUE TITLE
OSError: [Errno 121] Remote I/O error

### ISSUE THREAD

**Issue by DotEXEGaming** [chrisb2/pi_ina219#34]
As indicated by the title I am getting this error.
All code and error message is here: https://pastebin.com/KBh53Uq3
Running on a Raspberry Pi 4B 4GB.

Any help would be greatly appreciated, thanks!

**Comment by DotEXEGaming** [comment]
![image](https://user-images.githubusercontent.com/51715443/203610985-94ce6648-cb9c-4804-9d3d-63a7e70e633b.png)
circuit diagram *

**Comment by DotEXEGaming** [comment]
@chrisb2 sorry to at you but this is important for its use

**Comment by chrisb2** [comment]
Code and circuit look good. Please can you check that the device is visible on the i2c bus with:
`sudo i2cdetect -y 1`
as explain in [https://learn.adafruit.com/scanning-i2c-addresses/raspberry-pi](https://learn.adafruit.com/scanning-i2c-addresses/raspberry-pi), you should see it at address 0x40.

Chris

**Comment by DotEXEGaming** [comment]
I2C is enabled and when running `i2cdetect -y 1` the sensor is detected on 0x40

**Comment by chrisb2** [comment]
Searching in Google it seems the `OSError: [Errno 121] Remote I/O error` error is a pain to track down. Here are a few questions, sorry if you have already thought of some of these:

1. How long are leads between the Pi and the ina219?
2. Is the circuit diagram accurate or just a representation (sometimes the issue is something small)?

**Things to Try**
Add the following delay before you call `ina.configure()' in your program:
`utime.sleep_ms(10)'

Verify all the wires to the device are good and joints are solid? Are they soldered (dry joints?), or is this a prototype board (dodgy connection?)?

**Comment by DotEXEGaming** [comment]
The leads are bout 10cm long, and the circuit diagram is accurate minus the light and 12V battery. 
when running `cat /etc/os-release`:
```
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

I'm having issues with installing utime so i used `time.sleep(0.01)` instead but no luck.
All wires are solid dry joints.

**Comment by chrisb2** [comment]
Using a Pi 4B and latest Bullseye and a simple circuit like yours except bulb is a LED and series resistor powered from Pi 5V, I can make a measurement using _example.py_ with _busnum=1_. I think it most likely the issue is something to do with your circuit, can you try the following to try and eliminate where:
1. Replace your existing load under measurement with an LED and resistor power from Pi 5V (so same as my setup). Does this work?
2. If it does not work, that might indicate an issue with the ina219 breakout itself. If you have spare, trying swapping to it in the LED circuit.
3. If it does work, then there must be some issue with your actual load, perhaps you can use a process of elimination to try and work out the problem? If you have a logic analyzer this might be the time to use it.

Chris

**Comment by DotEXEGaming** [comment]
1. Same error.
2. The LED lights but the error persists.
3. I have not got any spare (soldered) boards currently.
Also the LED only lit when connecting to the screw terminals not the header (they should be the same?)

**Comment by chrisb2** [comment]
Header should work same as terminals. If you use a magnifying glass do the tracks look OK, or use a multimeter to check tracks.

Given LED circuit is not working its beginning to sound like your ina219 has a problem. So we are clear, below is a sketch of my LED circuit.

![circuit-ina219](https://user-images.githubusercontent.com/3087703/204207969-72e9254d-30c4-40b4-84f6-7f5d6bc5a2ff.jpg)

Chris

**Comment by DotEXEGaming** [comment]
To be clear, the LED does work now, yes, and I am using a separate power source with the ground shared with the pi.

**Comment by chrisb2** [comment]
So you can measure current and voltage with LED circuit?

**Comment by DotEXEGaming** [comment]
The LED lights, but the board gives the same error.

**Comment by chrisb2** [comment]
So I think your ina219 has a problem, I have never seen this simple led circuit fail with my library. The LED is always going to light unless the shunt resistor is dead, the ina219 chip on the breakout is another matter. I think you need to obtain a new breakout.

**Comment by DotEXEGaming** [comment]
Oh alright. I'll resolder another one and try then. Probably later today.

**Comment by DotEXEGaming** [comment]
After soldering a new board and closely inspecting the old one to see the ground pin wasn't even soldered on, it works! Thank you so much. Have a great day/evening what be it.
